const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],id=x=>document.getElementById(x);
const KEY='ericTeslaHubV44';
const ICON='<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>';
const DATA={
media:[['YouTube','https://www.youtube.com','Vidéos, musique et chaînes.'],['Twitch','https://www.twitch.tv','Lives gaming et événements.'],['myCANAL','https://www.canalplus.com','Films, séries et direct TV.'],['Netflix','https://www.netflix.com/','Films et séries.'],['Eurosport','https://www.eurosport.fr/','Directs et actualité sportive.'],['Spotify','https://open.spotify.com','Musique et playlists.'],['YouTube Music','https://music.youtube.com','Musique et clips.'],['Plex','https://www.plex.tv/watch-free/','Films et contenus gratuits.']],
games:[['GeoGuessr','https://www.geoguessr.com/fr','Explore le monde.'],['Board Game Arena','https://fr.boardgamearena.com/','Jeux de société en ligne.'],['itch.io HTML5','https://itch.io/games/html5','Jeux navigateur.'],['Lichess','https://lichess.org','Échecs légers et rapides.'],['CardGames.io','https://cardgames.io','Cartes, dames, solitaire.'],['CrazyGames','https://www.crazygames.com','Jeux HTML5 instantanés.']],
discover:[['Radio Garden','https://www.radio.garden/search','Radios du monde.'],['Flightradar24','https://www.flightradar24.com','Avions en temps réel.'],['EarthCam','https://www.earthcam.com/','Webcams du monde.'],['Arts & Culture','https://artsandculture.google.com/play','Expériences et jeux Google.'],['Akinator','https://www.akinator.com/','Devine ton personnage.'],['skribbl.io','https://skribbl.io','Dessiner et deviner.']],
tools:[['Waze Live Map','https://www.waze.com/live-map','Trafic et incidents.'],['Google Maps','https://www.google.com/maps','Recherche de lieux.'],['Windy','https://www.windy.com','Radar météo et vent.'],['Supercharge.info','https://forum.supercharge.info/latest','Nouveaux Superchargeurs et réseau.'],['Tesla Find Us','https://www.tesla.com/findus','Carte officielle Tesla.'],['Tesla Full Screen','https://teslafullscreen.com','Web Tesla en plein écran.'],['Fullify','https://fullify.app/','Launcher plein écran.'],['InCarWeb','https://incarweb.app/?lang=fr_FR','Portail web pour Tesla.'],['Dribe','https://dribe.app/','Sons moteur Tesla.']],
drive:[['Waze','https://www.waze.com/live-map','Trafic & incidents'],['Maps','https://www.google.com/maps','Recherche rapide'],['Windy','https://www.windy.com','Radar météo'],['Superchargeurs','https://www.tesla.com/findus','Réseau Tesla'],['Actu & Sport','#folder-news','Eurosport, Google Actu, L\'Équipe...'],['Curiosités','#folder-fun','Internet inutilement fascinant']],
live:[['Windy','https://www.windy.com','Radar pluie, neige, vent et orages'],['Waze Live Map','https://www.waze.com/live-map','Circulation, travaux, accidents'],['Supercharge.info','https://forum.supercharge.info/latest','Évolution du réseau Tesla']],
folders:{news:{title:'Actu & Sport',subtitle:'Un seul dossier, plusieurs sources.',links:[['Eurosport','https://www.eurosport.fr/','Sport, directs et résultats'],['Google Actualités','https://news.google.com/home?hl=fr&gl=FR&ceid=FR:fr','Toute l\'actualité personnalisable'],['L\'Équipe','https://www.lequipe.fr/','Sport en continu'],['franceinfo','https://www.franceinfo.fr/','Actualité France & monde'],['Numerama','https://www.numerama.com/','Tech, science et mobilité'],['Les Numériques','https://www.lesnumeriques.com/','High-tech et tests']]},fun:{title:'Inutile mais indispensable',subtitle:'Des sites qui ne servent à rien. Donc évidemment essentiels.',links:[['Neal.fun','https://neal.fun/','Expériences web brillamment absurdes'],['Drive & Listen','https://driveandlisten.app/','Rouler virtuellement dans des villes du monde'],['Bored Button','https://www.boredbutton.com/','Un bouton, un site aléatoire'],['WindowSwap','https://window-swap.com/','Regarder par la fenêtre de quelqu\'un ailleurs'],['Curious Crow','https://curiouscrow.vercel.app/','Coins étranges du web'],['Bored.com','https://www.bored.com/','Rabbit holes et curiosités']]}}};
const WX={0:['Ciel dégagé','Soleil'],1:['Peu nuageux','Éclaircies'],2:['Partiellement nuageux','Nuages'],3:['Couvert','Couvert'],45:['Brouillard','Brouillard'],48:['Brouillard givrant','Brouillard givrant'],51:['Bruine','Bruine'],53:['Bruine','Bruine'],55:['Bruine forte','Bruine'],56:['Bruine verglaçante','Verglas'],57:['Bruine verglaçante forte','Verglas'],61:['Pluie faible','Pluie'],63:['Pluie','Pluie'],65:['Pluie forte','Pluie forte'],66:['Pluie verglaçante','Verglas'],67:['Pluie verglaçante forte','Verglas'],71:['Neige faible','Neige'],73:['Neige','Neige'],75:['Neige forte','Neige forte'],77:['Grains de neige','Neige'],80:['Averses','Averses'],81:['Averses','Averses'],82:['Fortes averses','Fortes averses'],85:['Averses de neige','Neige'],86:['Fortes averses de neige','Neige forte'],95:['Orage','Orage'],96:['Orage avec grêle','Grêle possible'],99:['Orage violent avec grêle','Grêle possible']};
const getStore=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}},setStore=v=>localStorage.setItem(KEY,JSON.stringify(v));
let state=getStore();if(!state.custom)state.custom=[];if(!state.mode)state.mode='drive';setStore(state);
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function favicon(url){try{return `https://www.google.com/s2/favicons?sz=128&domain_url=${encodeURIComponent(new URL(url).origin)}`}catch(e){return''}}
function logo(url,name){const f=favicon(url);return `<div class="icon appIcon">${f?`<img src="${f}" alt="" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span class="fallbackLogo" style="display:none">${esc(name).slice(0,1)}</span>`:`<span class="fallbackLogo">${esc(name).slice(0,1)}</span>`}</div>`}
function tile([n,u,d]){return `<a class="tile externalLink" href="${u}" target="_blank" rel="noopener noreferrer"><span class="arrow">↗</span>${logo(u,n)}<div><strong>${esc(n)}</strong><br><small>${esc(d)}</small></div></a>`}
function folderTile(kind,title,desc){return `<button type="button" class="tile folderTile" data-folder="${kind}"><span class="arrow">＋</span><div class="icon folderIcon"><svg viewBox="0 0 24 24"><path d="M3 7h7l2 2h9v10H3z"/></svg></div><div><strong>${esc(title)}</strong><br><small>${esc(desc)}</small></div></button>`}
function quick([n,u,d]){if(u.startsWith('#folder-')){const kind=u.split('-')[1];return `<button type="button" class="quickTile quickButton" data-folder="${kind}"><span>${esc(n)}</span><small>${esc(d)}</small></button>`}return `<a class="quickTile externalLink" href="${u}" target="_blank" rel="noopener noreferrer"><span>${esc(n)}</span><small>${esc(d)}</small></a>`}
function stack([n,u,d]){return `<a class="stackItem externalLink" href="${u}" target="_blank" rel="noopener noreferrer"><strong>${esc(n)}</strong><span>${esc(d)}</span></a>`}
function renderStatic(){id('mediaGrid').innerHTML=DATA.media.map(tile).join('');id('gamesGrid').innerHTML=DATA.games.map(tile).join('');id('discoverGrid').innerHTML=folderTile('news','Actu & Sport','Eurosport, Google Actu, L\'Équipe et plus.')+folderTile('fun','Inutile mais indispensable','Neal.fun, Drive & Listen, Bored Button...')+DATA.discover.map(tile).join('');id('toolsGrid').innerHTML=DATA.tools.map(tile).join('');id('driveGrid').innerHTML=DATA.drive.map(quick).join('');id('liveGrid').innerHTML=DATA.live.map(stack).join('');bindFolders()}
const targets={drive:'#driveGrid',media:'#mediaGrid',games:'#gamesGrid',discover:'#discoverGrid',tools:'#toolsGrid'};
function renderCustom(){$$('.userTile').forEach(x=>x.remove());getStore().custom.forEach(x=>{const t=$(targets[x.section]||'#toolsGrid');if(!t)return;t.insertAdjacentHTML('beforeend',x.section==='drive'?`<a class="quickTile userTile externalLink" href="${esc(x.url)}" target="_blank"><span>${esc(x.name)}</span><small>Raccourci personnalisé</small></a>`:`<a class="tile userTile externalLink" href="${esc(x.url)}" target="_blank"><span class="arrow">↗</span>${logo(x.url,x.name)}<div><strong>${esc(x.name)}</strong><br><small>Raccourci personnalisé.</small></div></a>`)})}
function buildFolderModal(){if(id('folderModal'))return;const d=document.createElement('div');d.id='folderModal';d.className='folderModal';d.innerHTML='<div class="folderBox"><div class="folderHead"><div><h3 id="folderTitle">Dossier</h3><p id="folderSubtitle"></p></div><button type="button" class="folderClose" id="folderClose">×</button></div><div class="folderGrid" id="folderGrid"></div></div>';document.body.appendChild(d);id('folderClose').onclick=()=>d.classList.remove('show');d.onclick=e=>{if(e.target===d)d.classList.remove('show')}}
function openFolder(kind){const f=DATA.folders[kind];if(!f)return;id('folderTitle').textContent=f.title;id('folderSubtitle').textContent=f.subtitle;id('folderGrid').innerHTML=f.links.map(([n,u,d])=>`<a class="folderLink externalLink" href="${u}" target="_blank" rel="noopener noreferrer">${logo(u,n)}<strong>${esc(n)}</strong><span>${esc(d)}</span></a>`).join('');id('folderModal').classList.add('show')}
function bindFolders(){$$('[data-folder]').forEach(b=>b.onclick=e=>{e.preventDefault();openFolder(b.dataset.folder)})}
buildFolderModal();renderStatic();renderCustom();
const hero=$('.heroCard');
hero.innerHTML=`<div class="driveHeroPatch"><div class="driveHeroLayout"><div class="gpsMain"><div class="kicker">Vitesse GPS estimée</div><div><span class="num" id="gpsSpeed">--</span> <span class="unit">km/h</span></div><div class="small" id="gpsStateHero">En attente GPS</div></div><div class="clockPanel"><div class="kicker">Cockpit</div><div class="time" id="clock">--:--</div><div class="date" id="date">Chargement...</div></div><div class="gMain"><div class="kicker">Force G GPS approx.</div><div><span class="gnum" id="gForce">0.00</span> <span class="unit">G</span></div><div class="gmax">Pic <strong id="gMax">0.00 G</strong></div></div><div class="driveStatsPatch"><div><span>Météo</span><strong id="miniWeather">--</strong></div><div><span>Vent</span><strong id="miniWind">--</strong></div><div><span>Pluie</span><strong id="miniRain">--</strong></div><div><span>Mini / Maxi</span><strong id="miniRange">--</strong></div></div></div><div class="heroActions cockpitActions"><a class="cockpitAction externalLink" href="https://www.waze.com/live-map" target="_blank" rel="noopener noreferrer">Waze</a><a class="cockpitAction externalLink" href="https://www.google.com/maps" target="_blank" rel="noopener noreferrer">Maps</a><a class="cockpitAction externalLink" href="https://www.windy.com" target="_blank" rel="noopener noreferrer">Windy</a><button type="button" class="cockpitAction" data-folder="news">Actu & Sport</button><button type="button" class="cockpitAction" id="refreshWeather">Actualiser météo</button><button type="button" class="cockpitAction" id="addQuick">Ajouter</button></div></div><div class="loungeHeroPatch"><div class="kicker">Mode détente</div><h2>Pause. Médias, jeux et découverte.</h2><div class="small">Interface grand écran pour la démo et le divertissement à l'arrêt.</div><div class="loungeQuickPatch"><a class="externalLink" href="https://www.youtube.com" target="_blank" rel="noopener noreferrer"><strong>YouTube</strong><br><small>Vidéos</small></a><a class="externalLink" href="https://www.netflix.com/" target="_blank" rel="noopener noreferrer"><strong>Netflix</strong><br><small>Films & séries</small></a><a class="externalLink" href="https://www.geoguessr.com/fr" target="_blank" rel="noopener noreferrer"><strong>GeoGuessr</strong><br><small>Explorer</small></a><button type="button" data-folder="fun"><strong>Curiosités</strong><br><small>Inutile donc essentiel</small></button></div><div class="heroActions"><button type="button" class="cockpitAction" data-jump="media">Tous les médias</button><button type="button" class="cockpitAction" data-jump="arcade">Tous les jeux</button><button type="button" class="cockpitAction" data-jump="discover">Découvrir</button></div></div>`;
bindFolders();
const floating=document.createElement('div');floating.id='floatingCockpit';floating.className='floatingCockpit';floating.innerHTML='<div><span class="fcLabel">Vitesse</span><strong><b id="floatSpeed">--</b> <small>km/h</small></strong></div><div><span class="fcLabel">Heure</span><strong id="floatClock">--:--</strong></div><div><span class="fcLabel">Force G</span><strong><b id="floatG">0.00</b> <small>G</small></strong></div><div class="fcWeather"><span class="fcLabel">Météo</span><strong id="floatWeather">--</strong></div>';document.body.appendChild(floating);
function updateClock(){const n=new Date(),t=n.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),d=n.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});id('clock').textContent=t;id('date').textContent=d;id('floatClock').textContent=t}updateClock();setInterval(updateClock,1000);
function online(){id('onlineText').textContent=navigator.onLine?'En ligne':'Hors ligne';$('.dot').style.background=navigator.onLine?'var(--green)':'#f6b04d'}addEventListener('online',online);addEventListener('offline',online);online();
function mode(m){state=getStore();state.mode=m;setStore(state);document.body.classList.toggle('drive-mode',m==='drive');document.body.classList.toggle('lounge-mode',m==='lounge');$$('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('.topbar p').textContent=m==='drive'?'Cockpit épuré pour la route.':'Mode détente : médias, jeux et découverte.';floating.classList.toggle('modeOff',m!=='drive')}mode(state.mode);$$('.modeBtn').forEach(b=>b.onclick=()=>mode(b.dataset.mode));
function go(sec){if(['media','arcade','discover'].includes(sec))mode('lounge');if(sec==='drive')mode('drive');const t=id(sec);setTimeout(()=>t&&t.scrollIntoView({behavior:'smooth',block:'start'}),50)}$$('[data-go]').forEach(b=>b.onclick=e=>{e.preventDefault();go(b.dataset.go)});$$('[data-jump]').forEach(b=>b.onclick=()=>go(b.dataset.jump));
addEventListener('scroll',()=>{const y=scrollY||document.documentElement.scrollTop;floating.classList.toggle('show',y>330&&document.body.classList.contains('drive-mode'))},{passive:true});
let lastWeather=0;function weatherSummary(code,rain,snow,pp){let risk=(WX[code]||['',''])[1];if([56,57,66,67].includes(code))risk='Verglas / pluie verglaçante';else if([96,99].includes(code))risk='Orage avec grêle possible';else if([95].includes(code))risk='Orage possible';else if(snow>0)risk=`Neige ${snow.toFixed(1)} cm`;else if(rain>0)risk=`Pluie ${rain.toFixed(1)} mm`;else if(pp>=50)risk=`Risque de pluie ${pp}%`;return risk||'Conditions calmes'}
async function weather(lat,lon){try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&hourly=temperature_2m,precipitation_probability,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,rain_sum,snowfall_sum,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max&forecast_days=2&timezone=auto`,d=await(await fetch(u)).json(),c=d.current,w=WX[c.weather_code]||['Météo','Conditions'];id('weatherLabel').textContent=w[0];id('weatherTemp').textContent=Math.round(c.temperature_2m)+'°';id('weatherFeel').textContent='Ressenti '+Math.round(c.apparent_temperature)+'°';id('weatherWind').textContent=Math.round(c.wind_speed_10m)+' km/h';id('weatherLocation').textContent='Météo locale';id('weatherGlyph').innerHTML='<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M4 12h3M17 12h3"/></svg>';let ix=0,now=new Date();for(let i=0;i<d.hourly.time.length;i++){if(new Date(d.hourly.time[i])>=now){ix=i;break}}const rainNow=d.hourly.precipitation_probability[ix]??0;id('weatherRain').textContent=rainNow+'%';id('miniWeather').textContent=Math.round(c.temperature_2m)+'°';id('miniWind').textContent=Math.round(c.wind_speed_10m)+' km/h';id('miniRain').textContent=rainNow+'%';if(id('floatWeather'))id('floatWeather').textContent=Math.round(c.temperature_2m)+'° • '+w[1];id('hourly').innerHTML='';for(let i=ix;i<Math.min(ix+6,d.hourly.time.length);i++){const h=new Date(d.hourly.time[i]).getHours();id('hourly').insertAdjacentHTML('beforeend',`<div class="hour"><div>${h}h</div><strong>${Math.round(d.hourly.temperature_2m[i])}°</strong><div class="small">${d.hourly.precipitation_probability[i]}%</div></div>`)}const q=d.daily,code=q.weather_code[0],mn=Math.round(q.temperature_2m_min[0]),mx=Math.round(q.temperature_2m_max[0]),wind=Math.round(q.wind_speed_10m_max[0]),gust=Math.round(q.wind_gusts_10m_max[0]),rain=Number(q.rain_sum[0]||0),snow=Number(q.snowfall_sum[0]||0),pp=Number(q.precipitation_probability_max[0]||0),risk=weatherSummary(code,rain,snow,pp);id('dayMin').textContent=mn+'°';id('dayMax').textContent=mx+'°';id('dayWind').textContent=wind+' km/h';id('miniRange').textContent=mn+'° / '+mx+'°';id('dayRisk').textContent=risk;id('dayDetails').textContent=`Précipitations max ${pp}% • pluie ${rain.toFixed(1)} mm • neige ${snow.toFixed(1)} cm • rafales jusqu'à ${gust} km/h`;id('dayGlyph').innerHTML='<svg viewBox="0 0 24 24"><path d="M6 15a4 4 0 0 1 1-8A5 5 0 0 1 17.5 9 3.5 3.5 0 0 1 .5 7H7"/></svg>';lastWeather=Date.now();state=getStore();state.pos={lat,lon};setStore(state)}catch(e){id('weatherLocation').textContent='Météo indisponible'}}
id('refreshWeather').onclick=()=>{const s=getStore();if(s.pos)weather(s.pos.lat,s.pos.lon)};
let prev=null,shownSpeed=0,shownG=0,gMax=0;function hav(a,b,c,d){const R=6371000,r=x=>x*Math.PI/180,p=r(c-a),l=r(d-b),q=Math.sin(p/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(l/2)**2;return 2*R*Math.asin(Math.sqrt(q))}function bearing(a,b,c,d){const r=x=>x*Math.PI/180,y=Math.sin(r(d-b))*Math.cos(r(c)),x=Math.cos(r(a))*Math.sin(r(c))-Math.sin(r(a))*Math.cos(r(c))*Math.cos(r(d-b));return (Math.atan2(y,x)+2*Math.PI)%(2*Math.PI)}
function updateMotion(p){const c=p.coords,dt=prev?(p.timestamp-prev.t)/1000:0;let speedMS=Number.isFinite(c.speed)&&c.speed>=0?c.speed:null,stateTxt='GPS direct';let hdg=Number.isFinite(c.heading)&&c.heading>=0?c.heading*Math.PI/180:null;if(speedMS===null&&prev&&dt>.5&&dt<15){const dist=hav(prev.lat,prev.lon,c.latitude,c.longitude);speedMS=dist/dt;if(dist<Math.max(4,(c.accuracy||20)*.35))speedMS=0;stateTxt='GPS estimé'}if(hdg===null&&prev&&dt>.5&&dt<15)hdg=bearing(prev.lat,prev.lon,c.latitude,c.longitude);if(speedMS!==null){let kph=Math.min(speedMS*3.6,250);if(kph<3)kph=0;shownSpeed=kph===0&&shownSpeed<6?0:shownSpeed*.55+kph*.45;id('gpsSpeed').textContent=Math.round(shownSpeed);id('floatSpeed').textContent=Math.round(shownSpeed);id('gpsStateHero').textContent=stateTxt;if(prev&&dt>.5&&dt<6&&hdg!==null&&prev.hdg!==null&&prev.speedMS!==null){const vx=speedMS*Math.sin(hdg),vy=speedMS*Math.cos(hdg),pvx=prev.speedMS*Math.sin(prev.hdg),pvy=prev.speedMS*Math.cos(prev.hdg),acc=Math.hypot(vx-pvx,vy-pvy)/dt;let g=Math.min(acc/9.80665,2.5);if(kph<4)g=0;shownG=shownG*.65+g*.35;if(shownG<.015)shownG=0;gMax=Math.max(gMax,shownG);if(id('gForce'))id('gForce').textContent=shownG.toFixed(2);if(id('gMax'))id('gMax').textContent=gMax.toFixed(2)+' G';if(id('floatG'))id('floatG').textContent=shownG.toFixed(2)}}prev={lat:c.latitude,lon:c.longitude,t:p.timestamp,speedMS:speedMS??0,hdg};if(!lastWeather||Date.now()-lastWeather>600000)weather(c.latitude,c.longitude)}
function geoErr(){id('gpsStateHero').textContent='GPS indisponible';const s=getStore();if(s.pos&&!lastWeather)weather(s.pos.lat,s.pos.lon)}if(navigator.geolocation)navigator.geolocation.watchPosition(updateMotion,geoErr,{enableHighAccuracy:true,maximumAge:500,timeout:12000});else geoErr();
function close(){$$('.modal').forEach(m=>m.classList.remove('show'))}function open(x){id(x).classList.add('show')}$$('[data-close]').forEach(b=>b.onclick=close);$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)close()});id('addQuick').onclick=()=>open('addModal');
function manage(){const s=getStore(),box=id('customList');box.innerHTML=s.custom.length?s.custom.map((x,i)=>`<div class="customItem"><span><strong>${esc(x.name)}</strong> • ${esc(x.section)}</span><button data-del="${i}">Supprimer</button></div>`).join(''):'<div class="small">Aucun raccourci personnalisé.</div>';box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const q=getStore();q.custom.splice(+b.dataset.del,1);setStore(q);renderStatic();renderCustom();manage()});open('manageModal')}$$('[data-manage]').forEach(b=>b.onclick=manage);id('openAdd').onclick=()=>{close();open('addModal')};id('saveCustom').onclick=()=>{const name=id('newName').value.trim(),url=id('newUrl').value.trim(),section=id('newSection').value;if(!name||!/^https?:\/\//i.test(url)){alert('Ajoute un nom et une adresse commençant par https://');return}const s=getStore();s.custom.push({name,url,section});setStore(s);renderStatic();renderCustom();close()};if(id('themePulse'))id('themePulse').onclick=()=>document.body.classList.toggle('pulse-mode');