const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],id=x=>document.getElementById(x);
const KEY='ericTeslaHubV4';
const S={
media:[['YouTube','https://www.youtube.com','Vidéos, musique et chaînes.'],['Twitch','https://www.twitch.tv','Lives gaming et événements.'],['myCANAL','https://www.canalplus.com','Films, séries et direct TV.'],['Netflix','https://www.netflix.com/','Films, séries et contenus Netflix.'],['Spotify Web','https://open.spotify.com','Playlists et musique.'],['YouTube Music','https://music.youtube.com','Musique et playlists vidéo.'],['Plex','https://www.plex.tv/watch-free/','Films et contenus gratuits.'],['BigScrn','https://bigscrn.com/','Launcher vidéo plein écran pour Tesla.']],
games:[['Royal Bluff','https://floydem.github.io/Royal-bluff/','Ton jeu de cartes.'],['Tilt','https://floydem.github.io/tilt-game/','Ton jeu d\'adresse.'],['GeoGuessr','https://www.geoguessr.com/fr','Explore le monde et devine où tu es.'],['Board Game Arena','https://fr.boardgamearena.com/','Jeux de société en ligne.'],['itch.io HTML5','https://itch.io/games/html5','Des centaines de jeux navigateur.'],['Lichess','https://lichess.org','Échecs rapides et légers.'],['CardGames.io','https://cardgames.io','Solitaire, dames, cartes et plus.'],['CrazyGames','https://www.crazygames.com','Jeux HTML5 instantanés.']],
discover:[['Radio Garden','https://www.radio.garden/search','Radios du monde à explorer.'],['Flightradar24','https://www.flightradar24.com','Le ciel en temps réel.'],['EarthCam','https://www.earthcam.com/','Webcams live du monde entier.'],['Arts & Culture Play','https://artsandculture.google.com/play','Jeux et expériences Google.'],['Akinator','https://www.akinator.com/','Devine ton personnage.'],['skribbl.io','https://skribbl.io','Dessiner et deviner à plusieurs.']],
tools:[['ABRP','https://abetterrouteplanner.com','Planification EV.'],['PlugShare','https://www.plugshare.com','Bornes et avis.'],['Chargeprice','https://fr.chargeprice.app/','Comparer le coût des bornes.'],['Waze Live Map','https://www.waze.com/live-map','Trafic, incidents et état des routes.'],['Windy','https://www.windy.com','Radar météo et vent.'],['Supercharge.info','https://forum.supercharge.info/latest','Suivi communautaire du réseau.'],['Tesla Full Screen','https://teslafullscreen.com','Applications web en plein écran.'],['Fullify','https://fullify.app/','Launcher plein écran personnalisable.'],['InCarWeb','https://incarweb.app/?lang=fr_FR','Portail d\'outils et services pour Tesla.'],['Dribe','https://dribe.app/','Sons moteur Tesla.']],
drive:[['Waze','https://www.waze.com/live-map','Trafic & incidents'],['Maps','https://www.google.com/maps','Recherche rapide'],['ABRP','https://abetterrouteplanner.com','Planification EV'],['Chargeprice','https://fr.chargeprice.app/','Prix des bornes'],['PlugShare','https://www.plugshare.com','Bornes & avis'],['Tesla Full Screen','https://teslafullscreen.com','Web plein écran']],
live:[['Windy','https://www.windy.com','Radar pluie, vent et nuages'],['Waze Live Map','https://www.waze.com/live-map','Circulation, travaux, accidents'],['Supercharge.info','https://forum.supercharge.info/latest','Nouveaux sites et suivi du réseau']]
};
const wx={0:['Ciel dégagé','<circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M4.9 4.9 7 7M17 17l2 2M2 12h3M19 12h3"/>'],1:['Peu nuageux','<path d="M6 15a4 4 0 0 1 1-8A5 5 0 0 1 17.5 9 3.5 3.5 0 0 1 .5 7H7"/>'],2:['Partiellement nuageux','<path d="M6 15a4 4 0 0 1 1-8A5 5 0 0 1 17.5 9 3.5 3.5 0 0 1 .5 7H7"/>'],3:['Couvert','<path d="M6 16a4 4 0 0 1 1-8A5 5 0 0 1 18 10a3.5 3.5 0 0 1 0 7H6z"/>'],45:['Brouillard','<path d="M4 10h16M3 14h18M5 18h14"/>'],48:['Brouillard givrant','<path d="M4 10h16M3 14h18M5 18h14"/>'],51:['Bruine','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m9 17-1 2m5-2-1 2"/>'],53:['Bruine','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m9 17-1 2m5-2-1 2"/>'],55:['Bruine forte','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m8 17-1 2m4-2-1 2m4-2-1 2"/>'],61:['Pluie faible','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m9 17-1 3m5-3-1 3"/>'],63:['Pluie','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m8 17-1 3m4-3-1 3m4-3-1 3"/>'],65:['Pluie forte','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m7 17-1 3m4-3-1 3m4-3-1 3m4-3-1 3"/>'],71:['Neige faible','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="M8 18h2M9 17v2M14 18h2M15 17v2"/>'],73:['Neige','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="M8 18h2M9 17v2M14 18h2M15 17v2"/>'],75:['Neige forte','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="M7 18h2M8 17v2M12 18h2M13 17v2M17 18h2M18 17v2"/>'],80:['Averses','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m9 17-1 3m5-3-1 3"/>'],81:['Averses','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m8 17-1 3m4-3-1 3m4-3-1 3"/>'],82:['Fortes averses','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m7 17-1 3m4-3-1 3m4-3-1 3m4-3-1 3"/>'],95:['Orage','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m12 16-2 4h2l-1 2 4-5h-2l1-3z"/>'],96:['Orage & grêle','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m12 16-2 4h2l-1 2 4-5h-2l1-3z"/>'],99:['Orage violent','<path d="M6 13a4 4 0 0 1 1-8A5 5 0 0 1 18 7a3.5 3.5 0 0 1 0 7H6z"/><path d="m12 16-2 4h2l-1 2 4-5h-2l1-3z"/>']};
const icon='<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>';
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}},set=v=>localStorage.setItem(KEY,JSON.stringify(v));
let st=get();if(!st.custom)st.custom=[];if(!st.mode)st.mode='drive';if(!st.themePulse)st.themePulse='normal';set(st);
function tile([n,u,d]){return `<a class="tile" href="${u}" target="_blank" rel="noopener"><span class="arrow">↗</span><div class="icon">${icon}</div><div><strong>${n}</strong><br><small>${d}</small></div></a>`}
function quick([n,u,d]){return `<a class="quickTile" href="${u}" target="_blank" rel="noopener"><span>${n}</span><small>${d}</small></a>`}
function stack([n,u,d]){return `<a class="stackItem" href="${u}" target="_blank" rel="noopener"><strong>${n}</strong><span>${d}</span></a>`}
function renderStatic(){id('mediaGrid').innerHTML=S.media.map(tile).join('');id('gamesGrid').innerHTML=S.games.map(tile).join('');id('discoverGrid').innerHTML=S.discover.map(tile).join('');id('toolsGrid').innerHTML=S.tools.map(tile).join('');id('driveGrid').innerHTML=S.drive.map(quick).join('');id('liveGrid').innerHTML=S.live.map(stack).join('')}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const targets={drive:'#driveGrid',media:'#mediaGrid',games:'#gamesGrid',discover:'#discoverGrid',tools:'#toolsGrid'};
function renderCustom(){$$('.userTile').forEach(x=>x.remove());get().custom.forEach(x=>{const t=$(targets[x.section]||'#toolsGrid');t.insertAdjacentHTML('beforeend',x.section==='drive'?`<a class="quickTile userTile" href="${x.url}" target="_blank"><span>${esc(x.name)}</span><small>Raccourci personnalisé</small></a>`:`<a class="tile userTile" href="${x.url}" target="_blank"><span class="arrow">↗</span><div class="icon">${icon}</div><div><strong>${esc(x.name)}</strong><br><small>Raccourci personnalisé.</small></div></a>`)})}
renderStatic();renderCustom();
function clock(){const n=new Date();clockEl.textContent=n.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});id('date').textContent=n.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
const clockEl=$('#clock');clock();setInterval(clock,1000);
function online(){id('onlineText').textContent=navigator.onLine?'En ligne':'Hors ligne';$('.dot').style.background=navigator.onLine?'var(--green)':'#f6b04d'}addEventListener('online',online);addEventListener('offline',online);online();
function mode(m){st=get();st.mode=m;set(st);document.body.classList.toggle('drive-mode',m==='drive');$$('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));id('modeSummary').textContent=m==='drive'?'Conduite':'Détente'}mode(st.mode);$$('.modeBtn').forEach(b=>b.onclick=()=>mode(b.dataset.mode));
id('themePulse').onclick=()=>{st=get();st.themePulse=st.themePulse==='boost'?'normal':'boost';set(st);document.body.classList.toggle('pulse-mode',st.themePulse==='boost')};document.body.classList.toggle('pulse-mode',st.themePulse==='boost');
function charge(){const n=+id('soc').value,t=+id('target').value,p=+id('power').value,k=+id('kwh').value;if(t<=n||p<=0||k<=0){id('estimate').textContent='Entre une cible supérieure au niveau actuel.';id('miniCharge').textContent='--';return}const e=(t-n)/100*k,h=e/p,hh=Math.floor(h),mm=Math.round((h-hh)*60);id('estimate').innerHTML=`≈ <strong>${e.toFixed(1)} kWh</strong> à ajouter • <strong>${hh} h ${String(mm).padStart(2,'0')}</strong> à ${p.toFixed(1)} kW`;id('miniCharge').textContent=`${hh}h${String(mm).padStart(2,'0')}`}['soc','target','power','kwh'].forEach(id=>$('#'+id).oninput=charge);charge();
async function weather(lat,lon){try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&hourly=temperature_2m,precipitation_probability,weather_code&forecast_days=2&timezone=auto`,d=await(await fetch(u)).json(),c=d.current,w=wx[c.weather_code]||wx[0];id('weatherTemp').textContent=Math.round(c.temperature_2m)+'°';id('weatherLabel').textContent=w[0];id('weatherLocation').textContent='Météo locale';id('weatherFeel').textContent=Math.round(c.apparent_temperature)+'°';id('weatherWind').textContent=Math.round(c.wind_speed_10m)+' km/h';id('weatherGlyph').innerHTML=`<svg viewBox="0 0 24 24">${w[1]}</svg>`;let ix=0,n=new Date;for(let i=0;i<d.hourly.time.length;i++)if(new Date(d.hourly.time[i])>=n){ix=i;break}const rain=d.hourly.precipitation_probability[ix]??0;id('weatherRain').textContent=rain+'%';id('miniWeather').textContent=Math.round(c.temperature_2m)+'°';id('miniWind').textContent=Math.round(c.wind_speed_10m)+' km/h';id('miniRain').textContent=rain+'%';id('hourly').innerHTML=d.hourly.time.slice(ix,ix+6).map((t,j)=>{const i=ix+j,ww=wx[d.hourly.weather_code[i]]||wx[0];return `<div class="hour"><div>${new Date(t).getHours()}h</div><div class="ic"><svg viewBox="0 0 24 24">${ww[1]}</svg></div><strong>${Math.round(d.hourly.temperature_2m[i])}°</strong><span>${d.hourly.precipitation_probability[i]}%</span></div>`}).join('');st=get();st.pos={lat,lon};set(st)}catch(e){id('weatherLocation').textContent='Météo indisponible'}}
function updateWeather(){const f=()=>{st=get();st.pos?weather(st.pos.lat,st.pos.lon):id('weatherLocation').textContent='Autorise la localisation pour la météo locale'};navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>weather(p.coords.latitude,p.coords.longitude),f,{timeout:8000,maximumAge:600000}):f()}id('refreshWeather').onclick=updateWeather;updateWeather();
function traffic(){const h=new Date().getHours();id('routeTrafficLabel').textContent=(h>=22||h<=5)?'Nuit':'Trafic';id('routeTrafficValue').textContent=(h>=7&&h<=9)||(h>=16&&h<=19)?'Plus dense':(h>=22||h<=5?'Calme':'Fluide')}traffic();
$$('[data-go]').forEach(b=>b.onclick=()=>{const e=id(b.dataset.go);e&&e.scrollIntoView({behavior:'smooth'});$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.go===b.dataset.go))});
function open(n){id(n).classList.add('show')}function close(){$$('.modal').forEach(m=>m.classList.remove('show'))}$$('[data-close]').forEach(b=>b.onclick=close);$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)close()});id('addQuick').onclick=()=>open('addModal');id('openAdd').onclick=()=>{close();open('addModal')};
function manage(){st=get();id('customList').innerHTML=st.custom.length?st.custom.map((x,i)=>`<div class="customItem"><div class="meta"><strong>${esc(x.name)}</strong><span>${esc(x.url)}</span></div><button data-del="${i}">Supprimer</button></div>`).join(''):'<div class="customItem"><div class="meta"><strong>Aucun raccourci personnalisé</strong><span>Ajoute tes propres sites.</span></div></div>';$$('[data-del]').forEach(b=>b.onclick=()=>{st=get();st.custom.splice(+b.dataset.del,1);set(st);renderCustom();manage()});open('manageModal')}$$('[data-manage]').forEach(b=>b.onclick=manage);
id('saveCustom').onclick=()=>{const name=id('newName').value.trim(),url=id('newUrl').value.trim(),section=id('newSection').value;if(!name||!/^https?:\/\//i.test(url)){alert('Ajoute un nom et une adresse commençant par https://');return}st=get();st.custom.push({name,url,section});set(st);renderCustom();id('newName').value=id('newUrl').value='';close()};