const c=document.getElementById('c'),ctx=c.getContext('2d'),game=document.getElementById('game');
const overlay=document.getElementById('overlay'),scoreEl=document.getElementById('score'),distEl=document.getElementById('distance'),speedEl=document.getElementById('speed'),bestEl=document.getElementById('best');
let W=0,H=0,DPR=1,last=0,running=false,elapsed=0,score=0,distance=0,worldX=0,spawnTimer=0,collectTimer=0,flash=0;
let best=Number(localStorage.getItem('voltRunnerBest')||0);bestEl.textContent=best;
const car={x:0,y:0,vy:0,w:86,h:36,jumps:0,tilt:0};
let obstacles=[],collectibles=[],particles=[];
const rand=(a,b)=>a+Math.random()*(b-a);
function resize(){const r=game.getBoundingClientRect();DPR=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;c.width=Math.round(W*DPR);c.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);car.x=Math.max(100,W*.16);if(!running)car.y=groundY()-car.h}
function groundY(){return H*.78}
function roundRect(x,y,w,h,r,fill){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h);if(fill)ctx.fill()}
function palette(){const phase=(distance/900)%3;if(phase<1)return{sky1:'#8fd3ff',sky2:'#dff5ff',far:'#7aa4b5',mid:'#4d7580',near:'#244955',road:'#252a31',edge:'#353c45',sun:'#fff0a8'};if(phase<2)return{sky1:'#f6a66c',sky2:'#f7d2a4',far:'#8d6c78',mid:'#66556d',near:'#344052',road:'#26262d',edge:'#3a3943',sun:'#ffe9a5'};return{sky1:'#0e2446',sky2:'#21395e',far:'#253c5a',mid:'#1b3048',near:'#132535',road:'#181d24',edge:'#2a3038',sun:'#dbe9ff'}}
function drawSky(p){const g=ctx.createLinearGradient(0,0,0,groundY());g.addColorStop(0,p.sky1);g.addColorStop(1,p.sky2);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle=p.sun;ctx.globalAlpha=.75;ctx.beginPath();ctx.arc(W*.82,H*.18,34,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;drawHills(p.far,.12,H*.48,90);drawHills(p.mid,.22,H*.57,70);drawHills(p.near,.36,H*.67,52);drawDecor()}
function drawHills(color,speed,base,amp){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,H);const off=-(worldX*speed)%220;for(let x=off-220;x<=W+220;x+=110){const peak=base-amp*(.45+.55*Math.sin((x+worldX*.02)*.014+speed*9)**2);ctx.lineTo(x,base);ctx.quadraticCurveTo(x+55,peak,x+110,base)}ctx.lineTo(W,H);ctx.closePath();ctx.fill()}
function drawDecor(){const g=groundY(),off=-(worldX*.55)%260;for(let x=off-260;x<W+260;x+=260){const n=((Math.floor((x+worldX*.55)/260)%4)+4)%4;ctx.save();ctx.translate(x,g-10);if(n===0){ctx.strokeStyle='rgba(240,245,250,.72)';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-95);ctx.lineTo(0,0);ctx.stroke();for(let a=0;a<3;a++){ctx.save();ctx.translate(0,-95);ctx.rotate((worldX*.004)+a*Math.PI*2/3);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-34);ctx.stroke();ctx.restore()}}else if(n===1){ctx.fillStyle='rgba(18,48,42,.8)';ctx.beginPath();ctx.moveTo(-18,0);ctx.lineTo(0,-68);ctx.lineTo(18,0);ctx.fill();ctx.fillRect(-3,0,6,12)}else if(n===2){ctx.fillStyle='rgba(20,28,38,.5)';ctx.fillRect(-20,-44,18,44);ctx.fillRect(3,-68,24,68);ctx.fillRect(32,-36,16,36)}else{ctx.strokeStyle='rgba(255,255,255,.28)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-18,0);ctx.lineTo(0,-52);ctx.lineTo(18,0);ctx.stroke();ctx.beginPath();ctx.moveTo(-10,-24);ctx.lineTo(10,-24);ctx.stroke()}ctx.restore()}}
function drawRoad(p){const gy=groundY();ctx.fillStyle=p.road;ctx.fillRect(0,gy,W,H-gy);ctx.fillStyle=p.edge;ctx.fillRect(0,gy,W,8);ctx.strokeStyle='rgba(255,255,255,.35)';ctx.lineWidth=3;ctx.setLineDash([42,36]);ctx.lineDashOffset=-(worldX*.9)%78;ctx.beginPath();ctx.moveTo(0,gy+60);ctx.lineTo(W,gy+60);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(0,0,0,.18)';ctx.fillRect(0,gy+105,W,H-gy-105)}
function drawCar(){const gy=groundY(),air=(gy-car.h)-car.y;ctx.save();ctx.translate(car.x+car.w/2,car.y+car.h/2);ctx.rotate(car.tilt);ctx.shadowColor='rgba(0,0,0,.3)';ctx.shadowBlur=12;ctx.shadowOffsetY=7;ctx.fillStyle='#cfd3d6';roundRect(-43,-10,86,25,10,true);ctx.beginPath();ctx.moveTo(-24,-10);ctx.quadraticCurveTo(-10,-31,18,-29);ctx.quadraticCurveTo(31,-27,38,-10);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#182735';ctx.beginPath();ctx.moveTo(-16,-11);ctx.quadraticCurveTo(-5,-25,13,-24);ctx.lineTo(26,-11);ctx.closePath();ctx.fill();ctx.fillStyle='#b8c2ca';ctx.fillRect(-1,-24,2,13);ctx.fillStyle='#e82127';roundRect(-42,-4,7,7,3,true);ctx.fillStyle='#f4f7fa';roundRect(35,-3,7,6,3,true);ctx.fillStyle='#11161c';ctx.beginPath();ctx.arc(-25,16,10,0,Math.PI*2);ctx.arc(26,16,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#9aa3aa';ctx.beginPath();ctx.arc(-25,16,4,0,Math.PI*2);ctx.arc(26,16,4,0,Math.PI*2);ctx.fill();ctx.restore();if(air<3){ctx.fillStyle='rgba(0,0,0,.18)';ctx.beginPath();ctx.ellipse(car.x+43,gy+4,42,7,0,0,Math.PI*2);ctx.fill()}}
function obstacleShape(o){const gy=groundY();if(o.type==='cone'){ctx.fillStyle='#ff7a22';ctx.beginPath();ctx.moveTo(o.x+o.w/2,gy-o.h);ctx.lineTo(o.x+o.w,gy);ctx.lineTo(o.x,gy);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(o.x+5,gy-o.h*.45,o.w-10,5)}else if(o.type==='barrier'){ctx.fillStyle='#f5f5f5';roundRect(o.x,gy-o.h,o.w,o.h,5,true);ctx.fillStyle='#e82127';for(let i=0;i<3;i++){ctx.save();ctx.translate(o.x+8+i*26,gy-o.h+5);ctx.rotate(-.35);ctx.fillRect(0,0,10,o.h-10);ctx.restore()}ctx.fillStyle='#8e969e';ctx.fillRect(o.x+8,gy,5,13);ctx.fillRect(o.x+o.w-13,gy,5,13)}else if(o.type==='crate'){ctx.fillStyle='#8a633d';roundRect(o.x,gy-o.h,o.w,o.h,5,true);ctx.strokeStyle='#bc9163';ctx.lineWidth=3;ctx.strokeRect(o.x+5,gy-o.h+5,o.w-10,o.h-10);ctx.beginPath();ctx.moveTo(o.x+7,gy-o.h+7);ctx.lineTo(o.x+o.w-7,gy-7);ctx.moveTo(o.x+o.w-7,gy-o.h+7);ctx.lineTo(o.x+7,gy-7);ctx.stroke()}else{ctx.fillStyle='#0b0d10';ctx.beginPath();ctx.ellipse(o.x+o.w/2,gy-2,o.w/2,o.h/2,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#59616a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(o.x+4,gy-4);ctx.quadraticCurveTo(o.x+o.w*.5,gy-o.h,o.x+o.w-4,gy-4);ctx.stroke()}}
function spawnObstacle(){const types=['cone','barrier','crate','pothole'],type=types[Math.floor(Math.random()*types.length)];let w=34,h=52;if(type==='barrier'){w=72;h=50}if(type==='crate'){w=54;h=54}if(type==='pothole'){w=72;h=18}obstacles.push({x:W+80,w,h,type,passed:false})}
function spawnCollectible(){collectibles.push({x:W+100,y:groundY()-rand(95,190),r:14,got:false,phase:Math.random()*6.28})}
function rectsOverlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function jump(){if(!running)return;if(car.jumps<2){car.vy=car.jumps===0?-650:-560;car.jumps++;for(let i=0;i<8;i++)particles.push({x:car.x+22,y:car.y+car.h,vx:rand(-90,-20),vy:rand(-80,20),life:1})}}
function start(){running=true;elapsed=score=distance=worldX=spawnTimer=collectTimer=0;obstacles=[];collectibles=[];particles=[];flash=0;car.y=groundY()-car.h;car.vy=0;car.jumps=0;overlay.style.display='none';scoreEl.textContent='0';distEl.textContent='0';speedEl.textContent='1.0×';last=performance.now()}
function gameOver(){running=false;best=Math.max(best,Math.floor(score));localStorage.setItem('voltRunnerBest',String(best));bestEl.textContent=best;document.getElementById('overlayTitle').textContent='Fin de course';document.getElementById('overlayText').innerHTML=`Score : <strong>${Math.floor(score)}</strong> • Distance : <strong>${Math.floor(distance)} m</strong><br>Meilleur score : <strong>${best}</strong>`;document.getElementById('start').textContent='Rejouer';overlay.style.display='grid'}
function update(dt){if(!running)return;elapsed+=dt;const factor=Math.min(2.15,1+elapsed/70+distance/4200),speed=330*factor;worldX+=speed*dt;distance+=speed*dt*.035;score+=dt*14*factor;speedEl.textContent=factor.toFixed(1)+'×';scoreEl.textContent=Math.floor(score);distEl.textContent=Math.floor(distance);car.vy+=1850*dt;car.y+=car.vy*dt;const floor=groundY()-car.h;if(car.y>=floor){car.y=floor;car.vy=0;car.jumps=0}car.tilt=Math.max(-.18,Math.min(.18,car.vy/2600));spawnTimer-=dt;if(spawnTimer<=0){spawnObstacle();spawnTimer=rand(1.15,2.05)/Math.pow(factor,.25)}collectTimer-=dt;if(collectTimer<=0){if(Math.random()>.35)spawnCollectible();collectTimer=rand(2.4,4.2)}obstacles.forEach(o=>o.x-=speed*dt);collectibles.forEach(x=>{x.x-=speed*dt;x.phase+=dt*5});for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt*1.8}particles=particles.filter(p=>p.life>0);obstacles=obstacles.filter(o=>o.x>-120);collectibles=collectibles.filter(x=>x.x>-60&&!x.got);const hitbox={x:car.x+12,y:car.y+5,w:car.w-24,h:car.h-7};for(const o of obstacles){const ob={x:o.x+4,y:groundY()-o.h+4,w:o.w-8,h:Math.max(10,o.h-4)};if(rectsOverlap(hitbox,ob)){flash=.25;gameOver();break}if(!o.passed&&o.x+o.w<car.x){o.passed=true;score+=12}}for(const x of collectibles){const dx=(car.x+car.w/2)-x.x,dy=(car.y+car.h/2)-x.y;if(Math.hypot(dx,dy)<34){x.got=true;score+=35;for(let i=0;i<12;i++)particles.push({x:x.x,y:x.y,vx:rand(-110,110),vy:rand(-110,110),life:1})}}}
function drawCollectible(x){ctx.save();ctx.translate(x.x,x.y+Math.sin(x.phase)*5);ctx.rotate(x.phase*.12);ctx.shadowColor='rgba(90,167,255,.8)';ctx.shadowBlur=18;ctx.fillStyle='#67b6ff';ctx.beginPath();ctx.moveTo(-4,-16);ctx.lineTo(8,-5);ctx.lineTo(2,-3);ctx.lineTo(6,16);ctx.lineTo(-9,3);ctx.lineTo(-2,1);ctx.closePath();ctx.fill();ctx.restore()}
function drawParticles(){for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle='#75bdff';ctx.fillRect(p.x,p.y,4,4)}ctx.globalAlpha=1}
function draw(){const p=palette();drawSky(p);drawRoad(p);for(const x of collectibles)if(!x.got)drawCollectible(x);for(const o of obstacles)obstacleShape(o);drawParticles();drawCar();if(flash>0){ctx.fillStyle=`rgba(232,33,39,${Math.min(.45,flash)})`;ctx.fillRect(0,0,W,H)}}
function frame(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;if(flash>0)flash-=dt;update(dt);draw();requestAnimationFrame(frame)}
function handle(e){e.preventDefault();jump()}
c.addEventListener('pointerdown',handle,{passive:false});c.addEventListener('touchstart',handle,{passive:false});document.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();jump()}});document.getElementById('start').onclick=start;addEventListener('resize',resize);resize();requestAnimationFrame(frame);