const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen');
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));scrollTo({top:0,behavior:'smooth'})}
$('#homeBtn').onclick=()=>show('home');$('#finishHome').onclick=()=>show('home');$$('[data-open]').forEach(b=>b.onclick=()=>{const id=b.dataset.open;show(id);startMode(id)});
const QUIZ=[['Quelle planète est surnommée la planète rouge ?',['Mars','Vénus','Jupiter','Mercure'],0,'Science'],['Quel animal est le plus grand mammifère du monde ?',['Éléphant','Baleine bleue','Girafe','Requin-baleine'],1,'Animaux'],['Dans quel pays se trouve Tokyo ?',['Chine','Corée du Sud','Japon','Thaïlande'],2,'Géo'],['Combien de côtés possède un hexagone ?',['5','6','7','8'],1,'Logique'],['Quel groupe chante "Bohemian Rhapsody" ?',['Queen','U2','ABBA','Muse'],0,'Musique'],['Quel instrument possède généralement 88 touches ?',['Piano','Guitare','Violon','Trompette'],0,'Musique'],['Quelle console est sortie avant la PlayStation 2 ?',['Nintendo Switch','Xbox Series X','PlayStation 1','Wii'],2,'Jeux vidéo'],['Quel est le plus grand océan ?',['Atlantique','Indien','Pacifique','Arctique'],2,'Géo'],['Un siècle représente combien d’années ?',['10','50','100','1000'],2,'Culture'],['Quel animal peut dormir debout ?',['Cheval','Dauphin','Lapin','Koala'],0,'Animaux'],['Quel gaz les plantes absorbent-elles principalement ?',['Oxygène','CO₂','Hydrogène','Hélium'],1,'Science'],['Quel pays a la forme d’une botte ?',['Espagne','Italie','Grèce','Portugal'],1,'Géo'],['Dans Mario, comment s’appelle le frère de Mario ?',['Wario','Toad','Luigi','Yoshi'],2,'Jeux vidéo'],['Quel sport se joue à Roland-Garros ?',['Golf','Tennis','Rugby','Basket'],1,'Sport'],['Combien y a-t-il de minutes dans 2 h 30 ?',['120','130','150','180'],2,'Logique'],['Quel artiste est surnommé le "King of Pop" ?',['Prince','Elvis Presley','Michael Jackson','Bruno Mars'],2,'Musique'],['Quel est le symbole chimique de l’eau ?',['O2','CO2','H2O','NaCl'],2,'Science'],['Quel animal est connu pour changer de couleur ?',['Caméléon','Lynx','Panda','Loup'],0,'Animaux'],['Quelle ville est la capitale de l’Australie ?',['Sydney','Melbourne','Canberra','Perth'],2,'Géo'],['Dans Minecraft, quel matériau faut-il pour fabriquer une table d’enchantement ?',['Diamant','Cuivre','Fer','Quartz'],0,'Jeux vidéo'],['Combien font 12 × 8 ?',['84','96','108','88'],1,'Logique'],['Quel film met en scène un parc rempli de dinosaures clonés ?',['Avatar','Jurassic Park','Jumanji','King Kong'],1,'Cinéma'],['Quelle couleur obtient-on en mélangeant bleu et jaune ?',['Orange','Vert','Violet','Rouge'],1,'Culture'],['Quel continent abrite le Sahara ?',['Asie','Afrique','Amérique','Europe'],1,'Géo'],['Quelle est la vitesse approximative du son dans l’air ?',['34 km/h','340 m/s','3 400 km/s','30 m/s'],1,'Science'],['Quel personnage vit dans un ananas sous la mer ?',['Sonic','Bob l’éponge','Stitch','Kirby'],1,'Pop'],['Quel pays a remporté la Coupe du monde de football 2018 ?',['France','Argentine','Allemagne','Brésil'],0,'Sport'],['Quelle note vient après sol dans la gamme ?',['la','mi','do','fa'],0,'Musique'],['Quel est le plus petit nombre premier ?',['0','1','2','3'],2,'Logique'],['Quel oiseau ne vole pas et vit notamment en Antarctique ?',['Autruche','Pingouin / manchot','Aigle','Toucan'],1,'Animaux']];
let quizPool=[],quizIndex=0,quizScore=0,quizLocked=false;
function startQuiz(){quizPool=[...QUIZ].sort(()=>Math.random()-.5).slice(0,10);quizIndex=0;quizScore=0;renderQuiz()}
function renderQuiz(){quizLocked=false;$('#quizNext').style.display='none';$('#quizN').textContent=`${quizIndex+1}/10`;$('#quizScore').textContent=quizScore;const q=quizPool[quizIndex];$('#quizQ').innerHTML=`<span class="sub">${q[3]}</span><br>${q[0]}`;$('#quizChoices').innerHTML=q[1].map((x,i)=>`<button class="choice" data-i="${i}">${x}</button>`).join('');$$('#quizChoices .choice').forEach(b=>b.onclick=()=>answerQuiz(+b.dataset.i))}
function answerQuiz(i){if(quizLocked)return;quizLocked=true;const q=quizPool[quizIndex],buttons=$$('#quizChoices .choice');buttons[q[2]].classList.add('good');if(i===q[2])quizScore++;else buttons[i].classList.add('bad');$('#quizScore').textContent=quizScore;$('#quizNext').style.display='inline-flex'}
$('#quizNext').onclick=()=>{quizIndex++;if(quizIndex>=10){$('#finishTitle').textContent='Quiz terminé !';$('#finishText').textContent=`${quizScore}/10 bonnes réponses.`;show('finish')}else renderQuiz()};
const BAC_CATS=['Prénom','Pays ou ville','Animal','Métier','Objet','Aliment','Marque','Film / série','Personnage fictif','Quelque chose dans une maison','Sport','Mot drôle'];
let bacLetter='A',bacInterval=null,bacLeft=90,bacPoints=0;
function pickLetter(){const letters='ABCDEFGHJKLMNPRSTUV';bacLetter=letters[Math.floor(Math.random()*letters.length)];$('#bacLetter').textContent=bacLetter}
function buildBac(){const cats=[...BAC_CATS].sort(()=>Math.random()-.5).slice(0,8);$('#bacGrid').innerHTML=cats.map(c=>`<div class="bacRow"><label>${c}</label><input class="input bacInput" data-cat="${c}" placeholder="${bacLetter}..." autocomplete="off"></div>`).join('');$('#bacJudge').classList.remove('show');bacPoints=0;$('#bacScore').textContent=0}
function startBac(){clearInterval(bacInterval);bacLeft=90;$('#bacTimer').textContent=bacLeft;buildBac();bacInterval=setInterval(()=>{bacLeft--;$('#bacTimer').textContent=bacLeft;if(bacLeft<=0){clearInterval(bacInterval);judgeBac()}},1000)}
function judgeBac(){clearInterval(bacInterval);const rows=$$('.bacInput');$('#judgeList').innerHTML=rows.map((x,i)=>`<div class="judgeItem"><span><strong>${x.dataset.cat}</strong> : ${x.value||'—'}</span><div class="judgeBtns"><button class="mini" data-j="${i}" data-v="0">0</button><button class="mini" data-j="${i}" data-v="1">+1</button></div></div>`).join('');$('#bacJudge').classList.add('show');$$('[data-j]').forEach(b=>b.onclick=()=>{const val=+b.dataset.v;b.parentElement.querySelectorAll('button').forEach(x=>x.disabled=true);b.style.outline='2px solid var(--blue)';bacPoints+=val;$('#bacScore').textContent=bacPoints})}
$('#newLetter').onclick=()=>{pickLetter();buildBac()};$('#bacStart').onclick=startBac;
const DRAW_WORDS=['girafe','fusée','pizza','château','robot','volcan','licorne','sous-marin','dinosaure','parapluie','montgolfière','fantôme','guitare','skateboard','requin','phare','dragon','astronaute','caméléon','train','sushi','pirate','manette de jeu','tour Eiffel','bonhomme de neige'];
let drawWord='',drawShow=false,drawInterval=null,drawLeft=60;const dc=$('#drawCanvas'),dctx=dc.getContext('2d');let drawing=false,lastPt=null;
function resizeDraw(){const r=dc.getBoundingClientRect(),ratio=devicePixelRatio||1;dc.width=Math.round(r.width*ratio);dc.height=Math.round(r.height*ratio);dctx.setTransform(ratio,0,0,ratio,0,0);dctx.lineCap='round';dctx.lineJoin='round';dctx.lineWidth=5;dctx.strokeStyle='#111'}
function clearDraw(){dctx.save();dctx.setTransform(1,0,0,1,0,0);dctx.fillStyle='white';dctx.fillRect(0,0,dc.width,dc.height);dctx.restore()}
function point(e){const r=dc.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
dc.addEventListener('pointerdown',e=>{drawing=true;lastPt=point(e);dc.setPointerCapture?.(e.pointerId)});dc.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);dctx.beginPath();dctx.moveTo(lastPt.x,lastPt.y);dctx.lineTo(p.x,p.y);dctx.stroke();lastPt=p});addEventListener('pointerup',()=>drawing=false);
function newDrawWord(){drawWord=DRAW_WORDS[Math.floor(Math.random()*DRAW_WORDS.length)];drawShow=false;$('#drawPrompt').textContent='••••••';clearDraw()}
$('#revealPrompt').onclick=()=>{drawShow=!drawShow;$('#drawPrompt').textContent=drawShow?drawWord:'••••••'};$('#newPrompt').onclick=newDrawWord;$('#drawClear').onclick=clearDraw;$('#drawStart').onclick=()=>{clearInterval(drawInterval);drawLeft=60;$('#drawTimer').textContent=60;drawInterval=setInterval(()=>{drawLeft--;$('#drawTimer').textContent=drawLeft;if(drawLeft<=0)clearInterval(drawInterval)},1000)};
const TIMELINES=[[['Première PlayStation',1994],['Nintendo Wii',2006],['Nintendo Switch',2017],['PlayStation 5',2020]],[['Sortie de Jurassic Park',1993],['Titanic',1997],['Avatar',2009],['Avengers: Endgame',2019]],[['Premier iPhone',2007],['Instagram',2010],['TikTok international',2017],['ChatGPT public',2022]],[['Tour Eiffel achevée',1889],['Premier vol des frères Wright',1903],['Premier humain sur la Lune',1969],['Chute du mur de Berlin',1989]],[['Minecraft',2011],['Fortnite Battle Royale',2017],['Among Us',2018],['Palworld',2024]],[['Premier Toy Story',1995],['Shrek',2001],['La Reine des Neiges',2013],['Super Mario Bros. le film',2023]]];
let timelineRound=[],timelineSelected=[],timelineScore=0;
function newTimeline(){timelineRound=[...TIMELINES[Math.floor(Math.random()*TIMELINES.length)]].sort(()=>Math.random()-.5);timelineSelected=[];$('#timelineNext').style.display='none';$('#timelineAnswer').classList.remove('show');renderTimeline()}
function renderTimeline(){$('#timelineCards').innerHTML=timelineRound.map((x,i)=>`<div class="timelineCard ${timelineSelected.includes(i)?'selected':''}" data-i="${i}">${timelineSelected.includes(i)?`<span class="orderBadge">${timelineSelected.indexOf(i)+1}</span>`:''}<strong>${x[0]}</strong></div>`).join('');$$('.timelineCard').forEach(c=>c.onclick=()=>{const i=+c.dataset.i;if(timelineSelected.includes(i))timelineSelected=timelineSelected.filter(x=>x!==i);else if(timelineSelected.length<4)timelineSelected.push(i);renderTimeline()})}
$('#timelineReset').onclick=()=>{timelineSelected=[];renderTimeline()};$('#timelineCheck').onclick=()=>{if(timelineSelected.length!==4)return alert('Choisis les 4 cartes dans l’ordre.');const chosen=timelineSelected.map(i=>timelineRound[i]);const ok=chosen.every((x,i,a)=>i===0||a[i-1][1]<=x[1]);if(ok)timelineScore++;$('#timelineScore').textContent=timelineScore;const correct=[...timelineRound].sort((a,b)=>a[1]-b[1]);$('#timelineAnswer').innerHTML=(ok?'✅ Bien joué !':'❌ Pas tout à fait.')+'<br><br>'+correct.map(x=>`<strong>${x[1]}</strong> • ${x[0]}`).join('<br>');$('#timelineAnswer').classList.add('show');$('#timelineNext').style.display='inline-flex'};$('#timelineNext').onclick=newTimeline;
let reflexOn=false,reflexScore=0,reflexEnd=0,reflexRAF=0,targetTimer=0;
function spawnTarget(){if(!reflexOn)return;const a=$('#reflexArena'),r=a.getBoundingClientRect(),t=document.createElement('div');t.className='target';const size=78;t.style.left=Math.max(4,Math.random()*(r.width-size-8))+'px';t.style.top=Math.max(4,Math.random()*(r.height-size-8))+'px';t.onpointerdown=e=>{e.stopPropagation();reflexScore++;$('#reflexScore').textContent=reflexScore;t.remove();spawnTarget()};a.innerHTML='';a.appendChild(t);clearTimeout(targetTimer);targetTimer=setTimeout(()=>{if(t.isConnected)t.remove();spawnTarget()},700+Math.random()*700)}
function reflexLoop(){if(!reflexOn)return;const left=Math.max(0,(reflexEnd-performance.now())/1000);$('#reflexTime').textContent=left.toFixed(1);if(left<=0){reflexOn=false;$('#reflexArena').innerHTML=`<div style="display:grid;place-items:center;height:100%;font-size:30px">Score : <strong>${reflexScore}</strong></div>`;return}reflexRAF=requestAnimationFrame(reflexLoop)}
$('#reflexStart').onclick=()=>{reflexOn=true;reflexScore=0;$('#reflexScore').textContent=0;reflexEnd=performance.now()+20000;spawnTarget();cancelAnimationFrame(reflexRAF);reflexLoop()};$('#reflexArena').onpointerdown=()=>{if(reflexOn)reflexScore=Math.max(0,reflexScore-1);$('#reflexScore').textContent=reflexScore};
const PIXELS=[['🍕','Pizza'],['🦖','Dinosaure'],['🚀','Fusée'],['🦒','Girafe'],['🎸','Guitare'],['⚽','Ballon de football'],['🐼','Panda'],['🏰','Château'],['🚲','Vélo'],['🍉','Pastèque'],['👻','Fantôme'],['🎮','Manette de jeu'],['🐙','Poulpe'],['🌋','Volcan'],['🚁','Hélicoptère'],['🧩','Puzzle']];
const pc=$('#pixelCanvas'),pctx=pc.getContext('2d');let pixelItem=null,pixelLevel=1;
function resizePixel(){const r=pc.getBoundingClientRect(),ratio=devicePixelRatio||1;pc.width=Math.round(r.width*ratio);pc.height=Math.round(r.height*ratio);drawPixel()}
function drawPixel(){if(!pixelItem)return;const r=pc.getBoundingClientRect(),ratio=devicePixelRatio||1,w=r.width,h=r.height;pctx.setTransform(ratio,0,0,ratio,0,0);pctx.fillStyle='#0c1016';pctx.fillRect(0,0,w,h);const blocks=[24,16,10,6,3,1][Math.min(pixelLevel-1,5)];const small=document.createElement('canvas');small.width=Math.max(10,Math.floor(w/blocks));small.height=Math.max(10,Math.floor(h/blocks));const s=small.getContext('2d');s.fillStyle='#0c1016';s.fillRect(0,0,small.width,small.height);s.textAlign='center';s.textBaseline='middle';s.font=`${Math.floor(Math.min(small.width,small.height)*.68)}px serif`;s.fillText(pixelItem[0],small.width/2,small.height/2);pctx.imageSmoothingEnabled=false;pctx.drawImage(small,0,0,small.width,small.height,0,0,w,h)}
function nextPixel(){pixelItem=PIXELS[Math.floor(Math.random()*PIXELS.length)];pixelLevel=1;$('#pixelLevel').textContent=pixelLevel;$('#pixelAnswer').textContent='???';drawPixel()}
$('#pixelMore').onclick=()=>{pixelLevel=Math.min(6,pixelLevel+1);$('#pixelLevel').textContent=pixelLevel;drawPixel()};$('#pixelShow').onclick=()=>$('#pixelAnswer').textContent=pixelItem[1];$('#pixelNext').onclick=nextPixel;
function startMode(id){if(id==='quiz')startQuiz();if(id==='bac'){pickLetter();buildBac();$('#bacTimer').textContent=90}if(id==='draw'){setTimeout(()=>{resizeDraw();newDrawWord()},50)}if(id==='timeline')newTimeline();if(id==='pixel')setTimeout(()=>{resizePixel();nextPixel()},50);if(id==='reflex'){$('#reflexArena').innerHTML='';$('#reflexScore').textContent=0;$('#reflexTime').textContent='20.0'}}
addEventListener('resize',()=>{if($('#draw').classList.contains('active')){resizeDraw();clearDraw()}if($('#pixel').classList.contains('active'))resizePixel()});