(()=>{
const $=s=>document.querySelector(s);
const pc=$('#pixelCanvas');if(!pc)return;
const pctx=pc.getContext('2d');
const ITEMS=[
 {name:'Pizza',draw:(x,y,s)=>{pctx.fillStyle='#f3c45c';pctx.beginPath();pctx.moveTo(x-s*.45,y-s*.35);pctx.lineTo(x+s*.45,y);pctx.lineTo(x-s*.45,y+s*.35);pctx.closePath();pctx.fill();pctx.fillStyle='#d94b45';for(const [a,b] of [[-.15,-.14],[.05,.02],[-.18,.15]]){pctx.beginPath();pctx.arc(x+a*s,y+b*s,s*.07,0,Math.PI*2);pctx.fill()}pctx.strokeStyle='#9b5d2b';pctx.lineWidth=s*.08;pctx.beginPath();pctx.moveTo(x-s*.45,y-s*.35);pctx.lineTo(x-s*.45,y+s*.35);pctx.stroke()}},
 {name:'Fusée',draw:(x,y,s)=>{pctx.fillStyle='#e8edf2';pctx.beginPath();pctx.moveTo(x,y-s*.48);pctx.quadraticCurveTo(x+s*.25,y-s*.1,x+s*.18,y+s*.28);pctx.lineTo(x-s*.18,y+s*.28);pctx.quadraticCurveTo(x-s*.25,y-s*.1,x,y-s*.48);pctx.fill();pctx.fillStyle='#5aa7ff';pctx.beginPath();pctx.arc(x,y-s*.08,s*.09,0,Math.PI*2);pctx.fill();pctx.fillStyle='#e82127';pctx.beginPath();pctx.moveTo(x-s*.18,y+s*.1);pctx.lineTo(x-s*.35,y+s*.32);pctx.lineTo(x-s*.16,y+s*.28);pctx.fill();pctx.beginPath();pctx.moveTo(x+s*.18,y+s*.1);pctx.lineTo(x+s*.35,y+s*.32);pctx.lineTo(x+s*.16,y+s*.28);pctx.fill();pctx.fillStyle='#ffb84d';pctx.beginPath();pctx.moveTo(x-s*.08,y+s*.28);pctx.lineTo(x,y+s*.5);pctx.lineTo(x+s*.08,y+s*.28);pctx.fill()}},
 {name:'Dinosaure',draw:(x,y,s)=>{pctx.fillStyle='#64bf73';pctx.fillRect(x-s*.22,y-s*.2,s*.3,s*.42);pctx.fillRect(x+s*.02,y-s*.34,s*.28,s*.2);pctx.fillRect(x+s*.22,y-s*.26,s*.2,s*.08);pctx.fillRect(x-s*.35,y+s*.04,s*.16,s*.1);pctx.fillRect(x-s*.2,y+s*.2,s*.08,s*.28);pctx.fillRect(x+s*.02,y+s*.2,s*.08,s*.28);pctx.fillStyle='#10151c';pctx.fillRect(x+s*.19,y-s*.28,s*.035,s*.035)}},
 {name:'Manette',draw:(x,y,s)=>{pctx.fillStyle='#d7dce2';pctx.beginPath();pctx.moveTo(x-s*.32,y-s*.05);pctx.quadraticCurveTo(x-s*.46,y+s*.38,x-s*.18,y+s*.34);pctx.lineTo(x-s*.06,y+s*.16);pctx.lineTo(x+s*.08,y+s*.16);pctx.lineTo(x+s*.2,y+s*.34);pctx.quadraticCurveTo(x+s*.47,y+s*.38,x+s*.32,y-s*.05);pctx.quadraticCurveTo(x+s*.18,y-s*.28,x,y-s*.16);pctx.quadraticCurveTo(x-s*.18,y-s*.28,x-s*.32,y-s*.05);pctx.fill();pctx.strokeStyle='#151a20';pctx.lineWidth=s*.045;pctx.beginPath();pctx.moveTo(x-s*.22,y);pctx.lineTo(x-s*.08,y);pctx.moveTo(x-s*.15,y-s*.07);pctx.lineTo(x-s*.15,y+s*.07);pctx.stroke();pctx.fillStyle='#e82127';pctx.beginPath();pctx.arc(x+s*.18,y-s*.03,s*.04,0,Math.PI*2);pctx.fill();pctx.fillStyle='#5aa7ff';pctx.beginPath();pctx.arc(x+s*.28,y+s*.06,s*.04,0,Math.PI*2);pctx.fill()}},
 {name:'Volcan',draw:(x,y,s)=>{pctx.fillStyle='#7f543c';pctx.beginPath();pctx.moveTo(x-s*.45,y+s*.4);pctx.lineTo(x-s*.08,y-s*.18);pctx.lineTo(x+s*.08,y-s*.18);pctx.lineTo(x+s*.45,y+s*.4);pctx.closePath();pctx.fill();pctx.fillStyle='#e8502d';pctx.beginPath();pctx.arc(x,y-s*.28,s*.09,0,Math.PI*2);pctx.arc(x-s*.09,y-s*.38,s*.07,0,Math.PI*2);pctx.arc(x+s*.1,y-s*.42,s*.08,0,Math.PI*2);pctx.fill();pctx.strokeStyle='#ff9a3c';pctx.lineWidth=s*.06;pctx.beginPath();pctx.moveTo(x,y-s*.15);pctx.lineTo(x+s*.05,y+s*.18);pctx.stroke()}},
 {name:'Panda',draw:(x,y,s)=>{pctx.fillStyle='#f5f5f5';pctx.beginPath();pctx.arc(x,y,s*.34,0,Math.PI*2);pctx.fill();pctx.fillStyle='#111';pctx.beginPath();pctx.arc(x-s*.25,y-s*.25,s*.12,0,Math.PI*2);pctx.arc(x+s*.25,y-s*.25,s*.12,0,Math.PI*2);pctx.fill();pctx.beginPath();pctx.ellipse(x-s*.14,y-s*.04,s*.09,s*.12,-.4,0,Math.PI*2);pctx.ellipse(x+s*.14,y-s*.04,s*.09,s*.12,.4,0,Math.PI*2);pctx.fill();pctx.beginPath();pctx.arc(x,y+s*.08,s*.06,0,Math.PI*2);pctx.fill()}},
 {name:'Château',draw:(x,y,s)=>{pctx.fillStyle='#c8a56d';pctx.fillRect(x-s*.34,y-s*.08,s*.68,s*.43);pctx.fillRect(x-s*.43,y-s*.28,s*.18,s*.63);pctx.fillRect(x+s*.25,y-s*.28,s*.18,s*.63);for(const dx of [-.43,-.31,.25,.37])pctx.fillRect(x+dx*s,y-s*.36,s*.08,s*.09);pctx.fillStyle='#28384b';pctx.fillRect(x-s*.07,y+s*.13,s*.14,s*.22);pctx.fillRect(x-s*.34,y-s*.1,s*.08,s*.12);pctx.fillRect(x+s*.26,y-s*.1,s*.08,s*.12)}},
 {name:'Ballon',draw:(x,y,s)=>{pctx.fillStyle='#f5f5f5';pctx.beginPath();pctx.arc(x,y,s*.35,0,Math.PI*2);pctx.fill();pctx.strokeStyle='#111';pctx.lineWidth=s*.03;pctx.stroke();pctx.fillStyle='#111';pctx.beginPath();for(let i=0;i<5;i++){const a=-Math.PI/2+i*Math.PI*2/5;const r=i%2?s*.07:s*.13;pctx.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r)}pctx.closePath();pctx.fill();}}
];
let current=0,level=1;
function size(){const r=pc.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);pc.width=Math.max(20,Math.round(r.width*d));pc.height=Math.max(20,Math.round(r.height*d));pctx.setTransform(d,0,0,d,0,0);return{w:r.width,h:r.height,d}}
function drawClean(item,w,h){pctx.fillStyle='#0c1016';pctx.fillRect(0,0,w,h);item.draw(w/2,h/2,Math.min(w,h)*.72)}
function draw(){const {w,h}=size();drawClean(ITEMS[current],w,h);if(level>=6)return;const snap=document.createElement('canvas');snap.width=pc.width;snap.height=pc.height;snap.getContext('2d').drawImage(pc,0,0);const blocks=[34,24,16,10,6][level-1];const sw=Math.max(8,Math.floor(w/blocks)),sh=Math.max(6,Math.floor(h/blocks));const small=document.createElement('canvas');small.width=sw;small.height=sh;const sctx=small.getContext('2d');sctx.imageSmoothingEnabled=true;sctx.drawImage(snap,0,0,sw,sh);pctx.imageSmoothingEnabled=false;pctx.clearRect(0,0,w,h);pctx.drawImage(small,0,0,sw,sh,0,0,w,h);pctx.imageSmoothingEnabled=true}
function next(){current=Math.floor(Math.random()*ITEMS.length);level=1;$('#pixelLevel').textContent='1';$('#pixelAnswer').textContent='???';draw()}
$('#pixelMore').onclick=()=>{level=Math.min(6,level+1);$('#pixelLevel').textContent=String(level);draw()};
$('#pixelShow').onclick=()=>{$('#pixelAnswer').textContent=ITEMS[current].name;level=6;$('#pixelLevel').textContent='6';draw()};
$('#pixelNext').onclick=next;
const modeBtn=document.querySelector('[data-open="pixel"]');if(modeBtn){modeBtn.onclick=()=>{document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id==='pixel'));window.scrollTo({top:0,behavior:'smooth'});setTimeout(next,30)}}
window.addEventListener('resize',()=>{if(document.getElementById('pixel').classList.contains('active'))draw()});
})();